project_id                   = "sam-nash"
region                       = "asia-southeast1"
zone                         = "asia-southeast1-a"
instance_name                = "sam-nash-06"
service_account_id           = "new-sa-prj"
service_account_display_name = "Project Default SA"
project_number               = "180855126385"
