project_id                   = "gh-actions-1506"
region                       = "asia-southeast1"
zone                         = "asia-southeast1-a"
service_account_id           = "default-sa"
service_account_display_name = "Default Service Account"
project_number               = "180855126385"
