project_id                   = "sam-nash"
region                       = "asia-southeast1"
zone                         = "asia-southeast1-a"
service_account_id           = "project-sa"
service_account_display_name = "Project Default SA"
project_number               = "180855126385"
