# Cloudbuild file to read CSV file and print the values based on the input parameters
logsBucket: test_cloudbuild_logs

steps:
  - name: "alpine"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        apk add --no-cache bash

        while IFS=, read -r name1 name2 name3 name4 name5; do
            if [[ "$name1" == "new1" ]]; then
                echo "name1=$name1" && echo "name2=$name2" && echo "name3=$name3" && echo "name4=$name4" && echo "name5=$name5"
            fi
        done < "./config.csv"