logsBucket: test_cloudbuild_logs

steps:
  - name: "alpine"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        apk add --no-cache bash

        # Read the CSV file, skipping the header
        while IFS=, read -r name1 name2 name3 name4 name5; do
            echo "Processing line: $name1, $name2, $name3, $name4, $name5"  # Print each line for debugging
            if [[ "$name1" == "h1" ]]; then
                echo "name1=$name1"
                echo "name2=$name2"
                echo "name3=$name3"
                echo "name4=$name4"
                echo "name5=$name5"
            fi
        done < <(tail -n +2 "./config.csv")