name: Auth & Run GCloud CLI 

on:
  workflow_dispatch:

jobs:
  deploy:
    permissions: 
        contents: read
        id-token: write  
    runs-on: ubuntu-latest

    steps:
        # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

        # Authenticate to Google Cloud Platform
      - id: authenticate
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.GCP_SERVICE_ACCOUNT }}

        # Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ vars.GCP_PROJECT_ID_VAL }}
          version: '>= 363.0.0'

      - name: set credentials file
        run: >-
          gcloud auth login --cred-file=${{steps.authenticate.outputs.credentials_file_path}}

        # Run an arbitrary gcloud command to test authentication
      - name: List Google Cloud Projects
        run: |
          gcloud projects list
