name: Debug OIDC

# Trigger the workflow on push to the main branch only when this file iks modified
on:
  push:
    paths:
      - '.github/workflows/actions-oidc-debugger.yml'
    branches:
      - main

jobs:
  oidc_debugger:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    name: oidc debugger
    steps:
      - name: Checkout actions-oidc-debugger
        uses: actions/checkout@v3
        with:
          repository: github/actions-oidc-debugger
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ./.github/actions/actions-oidc-debugger
      - name: Debug OIDC Claims
        uses: ./.github/actions/actions-oidc-debugger
        with:
          audience: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
