name: Trigger Terraform Workflow

# Trigger on applying tag to master branch with a certain value example sam-nash
on:
  push:
    tags:
      - '[a-z]+-[a-z]+_[0-9]+'

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      # Debug step to print the GITHUB_REF
      - name: Print GITHUB_REF
        run: echo "GITHUB_REF=${GITHUB_REF}"

      - name: Extract the GCP Project Name from the Tag Name
        id: extract_tag
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          GCP_PROJECT=${TAG_NAME%_*}
          echo "GCP_PROJECT=$GCP_PROJECT" >> $GITHUB_OUTPUT
          echo "The Target GCP Project is: $GCP_PROJECT"


      - name: Trigger Terraform Workflow
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.GH_DISPATCH_PAT }}" \
            https://api.github.com/repos/sam-nash/gh-actions/dispatches \
            -d "{\"event_type\":\"terraform_apply\", \"client_payload\": {\"repository\": \"${{ github.repository }}\", \"gcp_project\": \"${{ steps.extract_tag.outputs.GCP_PROJECT }}\"}}"