name: Trigger Terraform Workflow

on:
  push:
    tags:
      - '[a-z]+-[a-z]+_PLAN_[0-9]+'
    branches:
      - 'feature/*'
  pull_request:
    types: [opened, closed]
    branches:
      - develop

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      # Debug step to print the GITHUB_REF
      - name: Print GITHUB_REF
        if: github.event_name == 'push'
        run: echo "GITHUB_REF=${GITHUB_REF}"

      - name: Print PR Information
        if: github.event_name == 'pull_request'
        run: |
          echo "PR Number: ${{ github.event.pull_request.number }}"
          echo "PR Action: ${{ github.event.action }}"
          echo "PR Merged: ${{ github.event.pull_request.merged }}"

      - name: Extract Information from Tag or PR
        id: extract_info
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            TAG_NAME=${GITHUB_REF#refs/tags/}
            TF_ACTION=$(echo $TAG_NAME | cut -d'_' -f2)
            GCP_PROJECT=$(echo $TAG_NAME | cut -d'_' -f1)
            echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
            echo "TF_ACTION=$TF_ACTION" >> $GITHUB_ENV
            echo "GCP_PROJECT=$GCP_PROJECT" >> $GITHUB_ENV
            echo "The Tag Name is: $TAG_NAME"
            echo "The Terraform Action is: $TF_ACTION"
            echo "The Target GCP Project is: $GCP_PROJECT"
          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
            if [[ "${{ github.event.action }}" == "closed" && "${{ github.event.pull_request.merged }}" == "true" ]]; then
              ACTION="apply"
            else
              ACTION="plan"
            fi
            echo "ACTION=$ACTION" >> $GITHUB_ENV
          fi

      - name: Trigger Terraform Workflow
        if: github.event_name == 'push'
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.GH_DISPATCH_PAT }}" \
            https://api.github.com/repos/sam-nash/gh-actions/dispatches \
            -d "{\"event_type\":\"terraform_${{ env.ACTION }}\", \"client_payload\": {\"repository\": \"${{ github.repository }}\", \"project_name\": \"${{ env.GCP_PROJECT }}\", \"tag_name\": \"${{ env.TAG_NAME }}\"}}"

      - name: Trigger Terraform Workflow for PR
        if: github.event_name == 'pull_request'
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.GH_DISPATCH_PAT }}" \
            https://api.github.com/repos/sam-nash/gh-actions/dispatches \
            -d "{\"event_type\":\"terraform_${{ env.ACTION }}\", \"client_payload\": {\"repository\": \"${{ github.repository }}\", \"pr_number\": \"${{ github.event.pull_request.number }}\", \"action\": \"${{ steps.extract_info.outputs.ACTION }}\"}}"